FROM java:8

ENV JAR myMavenProject1-0.0.1-SNAPSHOT.jar
ENV MAIN_CLASS com.mycompany.mavenproject1.HelloWorld

ADD "./target/myMavenProject1-0.0.1-SNAPSHOT.jar" "myMavenProject1-0.0.1-SNAPSHOT.jar"

CMD java  -jar myMavenProject1-0.0.1-SNAPSHOT.jar


